/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.AccountDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author vaish
 */
public class AccountManageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountManageJPanel
     */
    private JPanel UserProcessContainer;
    private AccountDirectory accountdirectory;
    
    AccountManageJPanel(JPanel UserProcessContainer, AccountDirectory accountdirectory) {
        initComponents();
        this.UserProcessContainer=UserProcessContainer;
        this.accountdirectory=accountdirectory;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmanageccount = new javax.swing.JButton();
        btncreateaccount = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnmanageccount.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        btnmanageccount.setText("MANAGE ACCOUNT");
        btnmanageccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmanageccountActionPerformed(evt);
            }
        });

        btncreateaccount.setFont(new java.awt.Font("Sylfaen", 1, 12)); // NOI18N
        btncreateaccount.setText("CREATE ACCOUNT");
        btncreateaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateaccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnmanageccount, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(604, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(btncreateaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(602, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(btnmanageccount, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(btncreateaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(456, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncreateaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateaccountActionPerformed
        // TODO add your handling code here:
        CreateJPanel panel=new CreateJPanel(UserProcessContainer,accountdirectory);
        UserProcessContainer.add("CreateAccountJPanel",panel);
        CardLayout cardlayout= (CardLayout) UserProcessContainer.getLayout();
        cardlayout.next(UserProcessContainer);
        
    }//GEN-LAST:event_btncreateaccountActionPerformed

    private void btnmanageccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmanageccountActionPerformed
        // TODO add your handling code here:
        ManageAccountJPanel manage=new ManageAccountJPanel(UserProcessContainer,accountdirectory);
        UserProcessContainer.add("ManageAccountJPanel",manage);
        CardLayout cardlayout= (CardLayout) UserProcessContainer.getLayout();
        cardlayout.next(UserProcessContainer);
    }//GEN-LAST:event_btnmanageccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreateaccount;
    private javax.swing.JButton btnmanageccount;
    // End of variables declaration//GEN-END:variables
}
