/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.supplier;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Supplier;

/**
 *
 * @author vaish
 */
public class SupplierPersonal extends javax.swing.JPanel {

    /**
     * Creates new form SupplierPersonal
     */

     JPanel workArea;
    Supplier supplier;
    
   
    public SupplierPersonal(JPanel workArea, Supplier supplier) {
        initComponents();
        
        this.workArea = workArea;
        this.supplier = supplier;
        
        txtname.setText(supplier.getProfile().getName()); 
        txtcontact.setText(String.valueOf(supplier.getProfile().getContactInformation())); 
        txtdescription.setText(supplier.getProfile().getDescription()); 
        
        txtname.setEnabled(false);
        txtcontact.setEnabled(false);
        txtdescription.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnupdatedescription = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblpname = new javax.swing.JLabel();
        btncontact = new javax.swing.JLabel();
        btndescription = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        txtdescription = new javax.swing.JTextField();
        btnupdatecontact = new javax.swing.JButton();
        btnupdatename = new javax.swing.JButton();
        lblphoto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        btnupdatedescription.setBackground(new java.awt.Color(255, 204, 51));
        btnupdatedescription.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        btnupdatedescription.setText("UPDATE DESCRIPTION");
        btnupdatedescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatedescriptionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("MY INFORMATION");

        lblpname.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        lblpname.setForeground(new java.awt.Color(255, 51, 0));
        lblpname.setText("NAME");

        btncontact.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        btncontact.setForeground(new java.awt.Color(255, 51, 0));
        btncontact.setText("CONTACT NO");

        btndescription.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        btndescription.setForeground(new java.awt.Color(255, 51, 0));
        btndescription.setText("DESCRIPTION");

        txtname.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtname.setForeground(new java.awt.Color(255, 51, 0));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
        });

        txtcontact.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtcontact.setForeground(new java.awt.Color(255, 51, 0));
        txtcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcontactKeyPressed(evt);
            }
        });

        txtdescription.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        txtdescription.setForeground(new java.awt.Color(255, 51, 0));
        txtdescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdescriptionKeyPressed(evt);
            }
        });

        btnupdatecontact.setBackground(new java.awt.Color(255, 204, 51));
        btnupdatecontact.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        btnupdatecontact.setText("UPDATE CONTACT");
        btnupdatecontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatecontactActionPerformed(evt);
            }
        });

        btnupdatename.setBackground(new java.awt.Color(255, 204, 51));
        btnupdatename.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        btnupdatename.setText("UPDATE NAME");
        btnupdatename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatenameActionPerformed(evt);
            }
        });

        lblphoto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblphoto.setForeground(new java.awt.Color(255, 51, 51));
        lblphoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblphoto.setText("CLICK TO ADD PICTURE");
        lblphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102)));
        lblphoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblphotoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(295, 295, 295))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblpname)
                            .addComponent(btncontact)
                            .addComponent(btndescription))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdescription, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(btnupdatename))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(btnupdatecontact))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(btnupdatedescription)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnupdatename)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btncontact)
                            .addComponent(txtcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnupdatecontact)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btndescription)
                            .addComponent(txtdescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnupdatedescription))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdatedescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatedescriptionActionPerformed
        // TODO add your handling code here:
       if (!txtdescription.isEnabled()) {
            txtdescription.setEnabled(true);
        } 
       else {
            String description = txtdescription.getText().trim(); 

            if (description.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter new description to update");
            } 
            else if (description.matches(".*[^a-zA-Z\\s].*")) {
                JOptionPane.showMessageDialog(this, "Description can only contain letters");
            } 
            else {
                supplier.getProfile().setDescription(description);
                JOptionPane.showMessageDialog(this, "DESCRIPTION UPDATED SUCCESSFULLY");
                txtdescription.setEnabled(false); 
            }
        }
    }//GEN-LAST:event_btnupdatedescriptionActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtnameKeyPressed

    private void txtcontactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontactKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtcontactKeyPressed

    private void txtdescriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescriptionKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtdescriptionKeyPressed

    private void btnupdatecontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatecontactActionPerformed
        // TODO add your handling code here:
        if (!txtcontact.isEnabled()) {
            txtcontact.setEnabled(true);
        }   
        else {
            String contact = txtcontact.getText().trim(); 

            if (contact.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter new contact information to update");
            } 
            else if (!contact.matches("^[0-9+]+$")) {
                JOptionPane.showMessageDialog(this, "Contact format is incorrect; it can only contain numbers and the plus sign (+)");
            } 
            else {
                long contactinfo = Long.parseLong(contact);
                supplier.getProfile().setContactInformation(contactinfo);
                JOptionPane.showMessageDialog(this, "CONTACT INFORMATION UPDATED SUCCESSFULLY");
                txtcontact.setEnabled(false); 
            }
        }
    }//GEN-LAST:event_btnupdatecontactActionPerformed

    private void btnupdatenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatenameActionPerformed
        // TODO add your handling code here:                                      

        if (!txtname.isEnabled()) {
            txtname.setEnabled(true);
        } 
        
        else {
            String name = txtname.getText().trim(); 

            if (name.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter a new name to update");
            }
            else if (!name.matches("^[a-zA-Z\\s]+$")) 
            {
                JOptionPane.showMessageDialog(this, "Name can only contain letters and spaces");
            }  
            else 
            {
                supplier.getProfile().setName(name);
                JOptionPane.showMessageDialog(this, "NAME UPDATED SUCCESSFULLY");
                txtname.setEnabled(false); 
            }
        }
    }//GEN-LAST:event_btnupdatenameActionPerformed

    private void lblphotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblphotoMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser= new JFileChooser();
        FileNameExtensionFilter filter= new FileNameExtensionFilter("4 extensions supported","jpg","png","jpeg","gif");
        fileChooser.setFileFilter(filter);
        int selected=fileChooser.showOpenDialog(null);
        if (selected == JFileChooser.APPROVE_OPTION){
            File file=fileChooser.getSelectedFile();
            String getSelectedImage= file.getAbsolutePath();
            //JOptionPane.showMessageDialog(null, getSelectedImage);
            ImageIcon imIco=new ImageIcon(getSelectedImage);
            Image imFit =imIco.getImage();
            Image imgFit=imFit.getScaledInstance(  lblphoto.getWidth(), lblphoto.getHeight(), Image.SCALE_SMOOTH);

            lblphoto.setIcon(new ImageIcon(imgFit));

        }
    }//GEN-LAST:event_lblphotoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btncontact;
    private javax.swing.JLabel btndescription;
    private javax.swing.JButton btnupdatecontact;
    private javax.swing.JButton btnupdatedescription;
    private javax.swing.JButton btnupdatename;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JLabel lblpname;
    public javax.swing.JTextField txtcontact;
    public javax.swing.JTextField txtdescription;
    public javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
